-- Test schema and tables for integration tests
-- Run this after CDC infrastructure is set up and capture agent is running

CONNECT TO TESTDB;

-- INVENTORY schema (used by deployment tests)
CREATE SCHEMA inventory AUTHORIZATION db2inst1;

CREATE TABLE inventory.PRODUCTS(ID INT NOT NULL PRIMARY KEY, NAME VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(255));
CREATE TABLE inventory.GENERAL_TABLE(ID INT NOT NULL PRIMARY KEY);
CREATE TABLE inventory.ORDERS(ID INT NOT NULL PRIMARY KEY, KEY INT NOT NULL, NAME VARCHAR(255) NOT NULL);
CREATE TABLE inventory.USERS(ID INT NOT NULL PRIMARY KEY, NAME VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(255) NOT NULL);

INSERT INTO inventory.GENERAL_TABLE(ID) VALUES (1);
INSERT INTO inventory.ORDERS (ID, KEY, NAME) VALUES (1, 1, 'one');
INSERT INTO inventory.ORDERS (ID, KEY, NAME) VALUES (2, 2, 'two');
INSERT INTO inventory.USERS (ID, NAME, DESCRIPTION) VALUES (1, 'giovanni', 'developer');
INSERT INTO inventory.USERS (ID, NAME, DESCRIPTION) VALUES (2, 'mario', 'developer');
INSERT INTO inventory.PRODUCTS (ID, NAME, DESCRIPTION) VALUES (1, 't-shirt', 'red hat t-shirt');
INSERT INTO inventory.PRODUCTS (ID, NAME, DESCRIPTION) VALUES (2, 'sweatshirt', 'blue ibm sweatshirt');

-- NATIVE schema (used by integration tests - default engine)
CREATE SCHEMA native AUTHORIZATION db2inst1;

CREATE TABLE native.PRODUCTS(ID INT NOT NULL PRIMARY KEY, NAME VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(255));
CREATE TABLE native.USERS(ID INT NOT NULL PRIMARY KEY, NAME VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(255) NOT NULL);

INSERT INTO native.PRODUCTS (ID, NAME, DESCRIPTION) VALUES (1, 't-shirt', 'red hat t-shirt');
INSERT INTO native.PRODUCTS (ID, NAME, DESCRIPTION) VALUES (2, 'sweatshirt', 'blue ibm sweatshirt');
INSERT INTO native.USERS (ID, NAME, DESCRIPTION) VALUES (1, 'giovanni', 'developer');
INSERT INTO native.USERS (ID, NAME, DESCRIPTION) VALUES (2, 'mario', 'developer');

-- ALTERNATIVE schema (used by integration tests - alternative engine)
CREATE SCHEMA alternative AUTHORIZATION db2inst1;

CREATE TABLE alternative.ORDERS(ID INT NOT NULL PRIMARY KEY, KEY INT NOT NULL, NAME VARCHAR(255) NOT NULL);

INSERT INTO alternative.ORDERS (ID, KEY, NAME) VALUES (1, 1, 'one');
INSERT INTO alternative.ORDERS (ID, KEY, NAME) VALUES (2, 2, 'two');
COMMIT;

-- Enable CDC on tables
CALL ASNCDC.ADDTABLE('INVENTORY', 'PRODUCTS');
CALL ASNCDC.ADDTABLE('INVENTORY', 'GENERAL_TABLE');
CALL ASNCDC.ADDTABLE('INVENTORY', 'ORDERS');
CALL ASNCDC.ADDTABLE('INVENTORY', 'USERS');
CALL ASNCDC.ADDTABLE('NATIVE', 'PRODUCTS');
CALL ASNCDC.ADDTABLE('NATIVE', 'USERS');
CALL ASNCDC.ADDTABLE('ALTERNATIVE', 'ORDERS');
UPDATE ASNCDC.IBMSNAP_REGISTER SET STATE='A' WHERE STATE='I';
COMMIT;

CONNECT RESET;
